var data={
    item1:{
        imgSrc:"../images/detailImg.png",
        title:"旁氏精致透白系列套装",
        price:"345.9",
        detail:"<h1>套装单品:</h1>"+
               "<ul>"+
                    "<li>1、精致透白防护日霜</li>"+
                     "<li>2、精致透白防护晚霜</li>"+
                     "<li>3、精致透白柔肤水</li>"+
                     "<li>4、精致透白深层洁面乳</li>"+
                "</ul>",
        activity:"<h1>活动内容:</h1>"+
                 "<p>全场旁氏产品消费满500元，减50元现金，满300元减20元现金，满100元，送精美小礼品一份。</p>"
    },
    item2:{
        title:"相宜本草四倍蚕丝凝白",
        imgSrc:"../images/_01.png",
        price:"130",
        detail:"<h1>套装单品:</h1>"+
            "<ul>"+
            "<li>1、四倍蚕丝洗面奶100g</li>"+
            "<li>2、精致透白防护晚霜</li>"+
            "<li>3、精致透白柔肤水</li>"+
            "<li>4、四倍蚕丝凝白保湿乳液100g</li>"+
            "</ul>",
        activity:"<h1>产品说明:</h1>"+
            "<p>相宜本草四倍蚕丝凝白3步曲美白滋润保湿补水润养。</p>"
    },
    item3:{
        title:"妮维雅男士洗面奶",
        imgSrc:"../images/_08.png",
        price:"28",
        detail:"",
        activity:"<h1>产品说明:</h1>"+
            "<p>妮维雅洗面奶男士控油劲爽洁面乳100g送50g去黑头0油。</p>"
    },
    item4:{
        title:"潘婷染烫损伤修复套装",
        imgSrc:"../images/_02.png",
        price:"128",
        detail:"<h1>套装单品:</h1>"+
            "<ul>"+
            "<li>1、潘婷洗发水600ml</li>"+
            "<li>2、发膜150ml</li>"+
            "<li>3、护发素600ml</li>"+
            "</ul>",
        activity:""
    },
    item5:{
        title:"清扬男士去屑洗发水",
        imgSrc:"../images/_09.png",
        price:"42.8",
        detail:"",
        activity:"<h1>产品说明:</h1>"+
        "<p>CLEAR/清扬男士去屑洗发水/露 清爽控油型400ml+100ml*2。</p>"
    },
    item6:{
        title:"高露洁 360度全面口腔美白牙膏",
        imgSrc:"../images/_03.png",
        price:"13.6",
        detail:"",
        activity:"<h1>产品说明:</h1>"+
            "<p>高露洁 360度全面口腔美白牙膏140克送护龈牙膏40克。</p>"
    },
    item7:{
        title:"洁丽雅纯棉强吸水舒适面巾",
        imgSrc:"../images/_10.png",
        price:"9.9/条",
        detail:"",
        activity:""
    },
    item8:{
        title:"立白冷水速效洗衣粉(无磷)2.008kg",
        imgSrc:"../images/_04.png",
        price:"17.8",
        detail:"",
        activity:"<h1>产品说明:</h1>"+
            "<p>立白冷水速效洗衣粉(无磷)2.008kg。</p>"
    },
    item9:{
        title:"飞科电吹风机",
        imgSrc:"../images/_11.png",
        price:"9",
        detail:"",
        activity:"<h1>产品说明:</h1>"+
            "<p>恒温护发2档1000W迷你可折叠 FH6203。</p>"
    },
    item10:{
        title:"五月花塑壳5磅保温瓶2.0L",
        imgSrc:"../images/_05.png",
        price:"19.9",
        detail:"",
        activity:"<h1>产品说明:</h1>"+
            "<p>恒温护发2档1000W迷你可折叠 FH6203。</p>"
    },
    item11:{
        title:"富光双层透明带盖玻璃杯",
        imgSrc:"../images/_12.png",
        price:"29",
        detail:"",
        activity:""
    },
    item12:{
        title:"金帝情缘榛子酱夹心巧克力99G",
        imgSrc:"../images/_07.png",
        price:"30.8",
        detail:"",
        activity:""
    },
    item13:{
        title:"费力罗8粒榛果威化巧克力 100G",
        imgSrc:"../images/_07.png",
        price:"36.9",
        detail:"",
        activity:""
    },
    item14:{
        title:"百利滋抹多口味饼干",
        imgSrc:"../images/_06.png",
        price:" 3.1/盒",
        detail:"",
        activity:"<h1>产品说明:</h1>"+
            "<p>百利滋抹茶香草、草莓牛奶 奶油香草装饰饼干45G。</p>"
    },
    item15:{
        title:"乐事无限薯片",
        imgSrc:"../images/_13.png",
        price:" 6.6/盒",
        detail:"",
        activity:"<h1>产品说明:</h1>"+
            "<p>呲呲烤肉  吮指烤肉  翡翠黄瓜  104g。</p>"
    }
}